server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # or "none", "validate", "create-drop" depending on your use case
application:
  jwt:
    secret: ${JWT_SECRET:secret}
    expiresAt: 846000
    headerPrefix: "Bearer "
    headerKey: "Authorization"
